[lint]
select = [
    "B",    # flake8-bugbear
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "SIM",  # flake8-simplify
    "UP",   # pyupgrade
]
ignore = [
    "B028", # no-explicit-stacklevel
]
