name: Docker

on:
  push:
    branches: [master]

jobs:
  cpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: build
      run: >
        docker build -t fthaler/stencil_benchmarks:cpu . -f dockerfiles/cpu.Dockerfile
    - name: test
      run: >
        docker run --rm fthaler/stencil_benchmarks:cpu /bin/bash -c "pip3 install -r /stencil_benchmarks/requirements-dev.txt && pytest -c /stencil_benchmarks/pytest.ini"
    - name: push
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u fthaler --password-stdin &&
        docker push fthaler/stencil_benchmarks:cpu &&
        docker logout
  cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuversion: ['10.1', '11.0']
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: build
      run: >
        docker build --build-arg CUDA_VERSION=${{ matrix.cuversion }} -t fthaler/stencil_benchmarks:cuda-${{ matrix.cuversion }} . -f dockerfiles/cuda.Dockerfile
    - name: test
      run: >
        docker run --rm fthaler/stencil_benchmarks:cuda-${{ matrix.cuversion }} /bin/bash -c "pip3 install -r /stencil_benchmarks/requirements-dev.txt && pytest -c /stencil_benchmarks/pytest.ini"
    - name: push
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u fthaler --password-stdin &&
        docker push fthaler/stencil_benchmarks:cuda-${{ matrix.cuversion }} &&
        docker logout
