name: Docker

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cpu, cuda]
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: build
      run: >
        docker build -t fthaler/stencil_benchmarks:${{ matrix.variant }} . -f dockerfiles/${{ matrix.variant }}.Dockerfile
    - name: test
      run: >
        docker run --rm fthaler/stencil_benchmarks:${{ matrix.variant }} /bin/bash -c "pip3 install -r /stencil_benchmarks/requirements-dev.txt && pytest -c /stencil_benchmarks/pytest.ini"
#   - name: push
#     run: >
#       echo ${{ secrets.DOCKER_TOKEN }} | docker login -u fthaler --password-stdin &&
#       docker push fthaler/stencil_benchmarks:${{ matrix.variant }} &&
#       docker logout
